### ISSUE TITLE
Cannot read property members

### ISSUE THREAD

**Issue by ImKitty** [timvandam/steam-gem-converter#1]
Node Version: 9.4.0
Tested on Version 7 and 8 aswell just to be sure. no change.

Update: This issue is caused by missing sharedsecret, which you say is not needed to work.

![bbe0a84fae59d18947a73d15e4dab52c](https://user-images.githubusercontent.com/24817996/35773222-fd909944-094b-11e8-9d6c-8fa1abebe2a9.png)

**Comment by timvandam** [comment]
Should be fixed now
